--기존 테이블삭제
DROP TABLE LIKEINFO CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE RESERVATION CASCADE CONSTRAINTS;
DROP TABLE HPINFO CASCADE CONSTRAINTS;
DROP TABLE USERINFO CASCADE CONSTRAINTS;

-- 기존 시퀀스 삭제
DROP SEQUENCE SEQ_RES_NUM;
DROP SEQUENCE SEQ_RE_NUM;
DROP SEQUENCE SEQ_HNUM;

-- 테이블 생성
-- 유저 테이블
CREATE TABLE USERINFO (
USER_ID VARCHAR2(20) NOT NULL,
USER_PWD VARCHAR2(20) NOT NULL,
USER_NAME VARCHAR2(20) NOT NULL,
USER_PNO VARCHAR2(20) NOT NULL,
USER_EMAIL VARCHAR2(40) NOT NULL,
USER_PHONE VARCHAR2(20) NOT NULL,
USER_AREA VARCHAR2(20) NOT NULL,
USER_FAVORITE VARCHAR2(1000),

CONSTRAINT USER_PK PRIMARY KEY (USER_ID)

);
-- 병원테이블
CREATE TABLE HPINFO (
HNUM NUMBER NOT NULL,
HP_CODE VARCHAR2(20) NOT NULL,
HP_NAME VARCHAR2(100) NOT NULL,
HP_INDEX VARCHAR2(20) NOT NULL,
HP_AREA VARCHAR2(20) NOT NULL,
HP_ADDRESS VARCHAR2(500) NOT NULL,
HP_OPEN NUMBER NOT NULL,
HP_CLOSE NUMBER NOT NULL,
HP_LUNCHST NUMBER NOT NULL,
HP_LUNCHFI NUMBER NOT NULL,
HP_PHONE VARCHAR2(20) NOT NULL,
HP_EMAIL VARCHAR2(40) NOT NULL,
HP_AVGPOINT NUMBER NOT NULL,
HP_DOCTOR1 VARCHAR2(20) NOT NULL,
HP_DOCTOR2 VARCHAR2(20) ,
HP_DOCTOR3 VARCHAR2(20) ,

CONSTRAINT HP_PK PRIMARY KEY (HP_CODE)

);


--예약테이블
CREATE TABLE RESERVATION (
RES_NUM NUMBER NOT NULL,
HP_CODE VARCHAR2(20) NOT NULL,
HP_NAME VARCHAR2(100) NOT NULL,
HP_INDEX VARCHAR2(20) NOT NULL,
HP_AREA VARCHAR2(20) NOT NULL,
HP_ADDRESS VARCHAR2(500) NOT NULL,
HP_PHONE VARCHAR2(20) NOT NULL,
USER_ID VARCHAR2(20) NOT NULL,
USER_NAME VARCHAR2(20) NOT NULL,
RES_TIME NUMBER NOT NULL,
RES_MIN NUMBER NOT NULL,
RES_DATE DATE NOT NULL,
HP_DOCTOR VARCHAR2(20) NOT NULL,
RES_CONTENT VARCHAR2(1000) NOT NULL,

CONSTRAINT RES_NUM_PK PRIMARY KEY (RES_NUM),
CONSTRAINT HP_CODE_FK2 FOREIGN KEY(HP_CODE) REFERENCES HPINFO(HP_CODE),
CONSTRAINT USER_FK2 FOREIGN KEY(USER_ID) REFERENCES USERINFO (USER_ID)

);
-- 5. 후기 테이블 생성 --
CREATE TABLE REVIEW(
RES_NUM NUMBER NOT NULL,
RE_NUM NUMBER NOT NULL,
USER_ID VARCHAR2(20) NOT NULL,
RE_TITLE VARCHAR2(50) NOT NULL,
RE_DATE DATE NOT NULL,
HP_CODE VARCHAR2(20) NOT NULL,
HP_NAME VARCHAR2(500) NOT NULL,
HP_AVGPOINT NUMBER NOT NULL,
HP_POINT1 NUMBER NOT NULL,
HP_POINT2 NUMBER NOT NULL,
HP_POINT3 NUMBER NOT NULL,
HP_POINT4 NUMBER NOT NULL,
HP_POINT5 NUMBER NOT NULL,
REVIEW VARCHAR2(1000) NOT NULL,
G_POINT NUMBER NOT NULL,
N_POINT NUMBER NOT NULL,

CONSTRAINT RE_NUM_PK PRIMARY KEY (RE_NUM),
CONSTRAINT HP_CODE_FK FOREIGN KEY(HP_CODE) REFERENCES HPINFO(HP_CODE),
CONSTRAINT USER_FK FOREIGN KEY(USER_ID) REFERENCES USERINFO (USER_ID),
CONSTRAINT RES_NUM_FK FOREIGN KEY(RES_NUM) REFERENCES RESERVATION(RES_NUM)
);


--좋아요 테이블 
CREATE TABLE LIKEINFO(
USER_ID VARCHAR2(20) NOT NULL,
RE_NUM NUMBER NOT NULL,
GOOD NUMBER DEFAULT '0',
BAD NUMBER DEFAULT '0',

CONSTRAINT USER_FK3 FOREIGN KEY(USER_ID) REFERENCES USERINFO (USER_ID),
CONSTRAINT RE_NUM_FK FOREIGN KEY(RE_NUM) REFERENCES REVIEW (RE_NUM)
);

--시퀀스 추가
CREATE SEQUENCE SEQ_RES_NUM;
CREATE SEQUENCE SEQ_RE_NUM;
CREATE SEQUENCE SEQ_HNUM;



-- 데이터 값 넣기
--회원 데이터 추가
INSERT INTO USERINFO(USER_ID,USER_PWD,USER_NAME,USER_PNO,USER_EMAIL,USER_PHONE,USER_AREA)
VALUES('admin123','admin123','사용자','951117-1111111','admin123@naver.com','010-1234-5678','강남구');

INSERT INTO USERINFO(USER_ID,USER_PWD,USER_NAME,USER_PNO,USER_EMAIL,USER_PHONE,USER_AREA)
VALUES('pado1054','a10541054','이동하','951117-1111111','pado1054@naver.com','010-4401-7471','강서구'); 

INSERT INTO USERINFO(USER_ID,USER_PWD,USER_NAME,USER_PNO,USER_EMAIL,USER_PHONE,USER_AREA)
VALUES('daone123','a123123','추다원','951111-2111111','daone123@naver.com','010-1234-5678','강북구');


--병원 데이터 추가
INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GN_1', '강남내과','내과', '강남구', '역삼동545-1', 9, 17, 13, 14, '010-4444-4444', 'moon@naver.com', 0, '돌팔이', '금팔이', '은팔이');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GN_2', '강남치과','치과', '강남구', '역삼동125-1', 9, 17, 13, 14, '010-4444-4444', 'moon@naver.com', 0, '돌팔이', '금팔이', '은팔이');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GN_3', '강남안과','안과', '강남구', '역삼동5345-1', 9, 17, 13, 14, '010-4444-4444', 'moon@naver.com', 0, '돌팔이', '금팔이', '은팔이');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GD_1', '강동내과','내과', '강동구', '천호동 410-106', 9, 17, 13, 14, '010-4444-4444', 'moon@naver.com', 0, '돌팔이', '금팔이', '은팔이');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GD_2', '강동정형외과','정형외과', '강동구', '천호동 410-154', 9, 17, 13, 14, '010-4444-4444', 'moon@naver.com', 0, '돌팔이', '금팔이', '은팔이');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GD_3', '강동이비인후과','이비인후과', '강동구', '천호동 432-106', 9, 17, 13, 14, '010-4444-4444', 'moon@naver.com', 0, '돌팔이', '금팔이', '은팔이');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GS_1', '강서피부과','피부과', '강서구', '화곡동545-1', 9, 17, 13, 14, '010-4444-4444', 'moon@naver.com', 0, '돌팔이', '금팔이', '은팔이');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GS_2', '강서치과','치과', '강서구', '화곡동125-1', 9, 17, 13, 14, '010-4444-4444', 'moon@naver.com', 0, '돌팔이', '금팔이', '은팔이');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GS_3', '강서안과','안과', '강서구', '화곡동5345-1', 9, 17, 13, 14, '010-4444-4444', 'moon@naver.com', 0, '돌팔이', '금팔이', '은팔이');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GB_1', '강북내과','내과', '강북구', '미아동 410-106', 9, 17, 13, 14, '010-4444-4444', 'moon@naver.com', 0, '돌팔이', '금팔이', '은팔이');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GB_2', '강북가정의학과','가정의학과', '강북구', '미아동 410-154', 9, 17, 13, 14, '010-4444-4444', 'moon@naver.com', 0, '돌팔이', '금팔이', '은팔이');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GB_3', '강북이비인후과','이비인후과', '강북구', '미아동 432-106', 9, 17, 13, 14, '010-4444-4444', 'moon@naver.com', 0, '돌팔이', '금팔이', '은팔이');



--양천구--
INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'YC_1', '양천안과','안과', '양천구', '목5동535-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'YC_2', '양천내과','내과', '양천구', '목동435', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'YC_3', '양천가정의학과','가정의학과', '양천구', '목1동35-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'YC_4', '양천소아','소아청소년과', '양천구', '목3동54-9', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'YC_5', '양천정형외과','정형외과', '양천구', '목4동52-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

--은평구--
INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'EP_1', '은평안과','안과', '은평구', '구산동35-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'EP_2', '은평내과','내과', '은평구', '신사1동435', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'EP_3', '은평피부과','피부과', '은평구', '갈현1동35-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'EP_4', '은평소아','소아청소년과', '은평구', '응암1동54-9', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'EP_5', '은평가정의학과','가정의학과', '은평구', '갈현동52-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

--종로구--
INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'JN_1', '종로안과','안과', '종로구', '관수동535-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'JN_2', '종로내과','내과', '종로구', '옥인동435', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'JN_3', '종로피부과','피부과', '종로구', '와룡동35-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'JN_4', '종로소아','소아청소년과', '종로구', '연지동54-9', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'JN_5', '종로정형외과','정형외과', '종로구', '중학동52-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

--중구--
INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'DG_1', '중구안과','안과', '중구', '광희동535-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'DG_2', '중구내과','내과', '중구', '다동435', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'DG_3', '중구피부과','피부과', '중구', '장교동35-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'DG_4', '중구치과','치과', '중구', '쌍림동54-9', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'DG_5', '중구정형외과','정형외과', '중구', '정동52-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

--------------------------------------------경연-------------------------------------------
--서초구--
INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'SC_1', '서초치과','치과', '서초구', '반포동535-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'SC_2', '서초이비인후과','이비인후과', '서초구', '염곡동435', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'SC_3', '서초피부과','피부과', '서초구', '내곡동35-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'SC_4', '서초소아','소아청소년과', '서초구', '우면동54-9', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'SC_5', '서초가정의학과','가정의학과', '서초구', '반포1동52-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

--송파구--
INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'SP_1', '송파치과','치과', '송파구', '가락1동535-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'SP_2', '송파이비인후과','이비인후과', '송파구', '거여동435', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'SP_3', '송파피부과','피부과', '송파구', '문정1동35-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'SP_4', '송파소아','소아청소년과', '송파구', '오륜동54-9', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'SP_5', '송파정형외과','정형외과', '송파구', '풍납동52-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

--영등포구--
INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'YDP_1', '영등포치과','치과', '영등포구', '대림1동535-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'YDP_2', '영등포이비인후과','이비인후과', '영등포구', '도림동435', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'YDP_3', '영등포피부과','피부과', '영등포구', '당산1동35-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'YDP_4', '영등포소아','소아청소년과', '영등포구', '양화동54-9', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'YDP_5', '영등포정형외과','정형외과', '영등포구', '여의도동52-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

--용산구--
INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'YS_1', '바른이치과','치과', '용산구', '갈월동535-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'YS_2', '코앤코','이비인후과', '용산구', '이촌동435', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'YS_3', '더페이스','피부과', '용산구', '도원동35-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'YS_4', '아이꿈','소아청소년과', '용산구', '신창동54-9', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'YS_5', '기대찬정형외과','정형외과', '용산구', '신계동52-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

--------------------------------------------수연-------------------------------------------

--노원구--
INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'NW_1', '노원안과','안과', '노원구', '공릉동535-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'NW_2', '노원내과','내과', '노원구', '하계동435', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'NW_3', '노원피부과','피부과', '노원구', '상계1동35-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'NW_4', '노원소아','소아청소년과', '노원구', '중계동54-9', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'NW_5', '노원정형외과','정형외과', '노원구', '중계본동52-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

--동대문구--
INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'DDM_1', '동대문안과','안과', '동대문구', '신설동35-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'DDM_2', '동대문내과','내과', '동대문구', '용두동435', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'DDM_3', '동대문피부과','피부과', '동대문구', '용신동35-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'DDM_4', '동대문소아','소아청소년과', '동대문구', '전능동54-9', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'DDM_5', '동대문정형외과','정형외과', '동대문구', '이문동52-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

--동작구--
INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'DJ_1', '동작구안과','안과', '동작구', '대방동535-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'DJ_2', '동작구내과','내과', '동작구', '동작동435', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'DJ_3', '동작피부과','피부과', '동작구', '사당4동35-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'DJ_4', '동작소아','소아청소년과', '동작구', '신대방동54-9', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'DJ_5', '동작정형외과','정형외과', '동작구', '흑석동52-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

--도봉구--
INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'DB_1', '도봉구안과','안과', '도봉구', '방학2동535-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'DB_2', '도봉구내과','내과', '도봉구', '창동435', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'DB_3', '도봉피부과','피부과', '도봉구', '쌍문1동35-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'DB_4', '도봉소아','소아청소년과', '도봉구', '도봉2동54-9', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'DB_5', '도봉정형외과','정형외과', '도봉구', '도봉동52-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, '김수근', '송종기', '운종신');

--------------------------------------------석영-------------------------------------------
-- 마포구 병원 
INSERT INTO HPINFO VALUES(SEQ_HNUM.nextval,'MP_1','연세MY바른이치과의원','치과','마포구','동교동 166-13 삼양세븐스프링스',10,18,13,14,'02-337-2282','http://www.mybaruni.com/',0,'김민정','이예벗','김민영');
INSERT INTO HPINFO VALUES(SEQ_HNUM.nextval,'MP_2','마인드피부과의원','피부과','마포구','동교동 166-13 삼양세븐스프링스 3층',10,20,13,14,'02-333-3133','http://mindskin.co.kr/',0,'이홍선','유지영','김서완');
INSERT INTO HPINFO VALUES(SEQ_HNUM.nextval,'MP_3','내안애내과의원','내과','마포구','도화동 563 마포아크로타워',9,18,13,14,'02-712-4800','http://www.neane.kr/',0,'서정필','정미연','강현주');

-- 서대문구 병원
INSERT INTO HPINFO VALUES(SEQ_HNUM.nextval,'SDM_1','잎사귀치과병원','치과','서대문구','연세로5길 26','10','19','13','14','02-3141-4947','http://www.5ok.co.kr/',0,'이상용','이은준','이동주');
INSERT INTO HPINFO VALUES(SEQ_HNUM.nextval,'SDM_2','서대문하나이비인후과의원','이비인후과','서대문구','충정로2가 5-4 공화당빌딩','09','18','13','14','02-364-9925','http://www.hanaentnetwork.co.kr/',0,'남규준','곽보경','없음');
INSERT INTO HPINFO VALUES(SEQ_HNUM.nextval,'SDM_3','박성균소아청소년의원','소아청소년과','서대문구','문화촌길 6 승화빌딩 5층','09','18','13','14','02-379-8275','없음',0,'박성균','없음','없음');

--성동구 병원
INSERT INTO HPINFO VALUES(SEQ_HNUM.nextval,'SD_1','369다움의원','피부과','성동구','행당동 168-151 왕십리민자역사 비트플렉스 4층 365의원','11','20','13','14','02-2297-1755','http://www.dawoomclinic.co.kr/',0,'윤영현','없음','없음');
INSERT INTO HPINFO VALUES(SEQ_HNUM.nextval,'SD_2','성수아침이비인후과의원','이비인후과','성동구','성수동2가 289-10 제강빌딩 501호','09','19','13','14','02-2205-1151','http://sungsuent.kr/',0,'김범석','없음','없음');
INSERT INTO HPINFO VALUES(SEQ_HNUM.nextval,'SD_3','준정형외과의원','정형외과','성동구','성수동1가 14-17 안동빌딩 5층','09','20','13','14','02-2038-9941','http://junos9941.modoo.at/',0,'오정석','권상민','오민석');

--성북구 병원
INSERT INTO HPINFO VALUES(SEQ_HNUM.nextval,'SB_1','빈센트치과의원','치과','성북구','동소문동6가 143-5 해피엔딩 오피스텔 3층','10','21','13','14','02-923-2875','http://www.vincentdent.com/',0,'김태현','조수연','없음');
INSERT INTO HPINFO VALUES(SEQ_HNUM.nextval,'SB_2','우리기쁜산부인과의원','산부인과','성북구','종암동 3-539','09','18','13','14','02-2039-1000','http://www.wejoyful.com/',0,'김낙근','윤형동','김정은');
INSERT INTO HPINFO VALUES(SEQ_HNUM.nextval,'SB_3','고운숨결내과의원','내과','성북구','안암동2가 98-1 3,4층','09','17','13','14','02-925-9696','http://www.sumsori.com/',0,'김태현','김낙근','권상민');

--------------------------------------------우희-------------------------------------------
--관악구--
INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GW_1', '365밝은안과','안과', '관악구', '신림동1424-28', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GW_3', '유라인치과','치과', '관악구', '신림동1422-5', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GW_2', '연세건우정형외과','정형외과', '관악구', '봉천동689-12', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GW_4', '미앤미피부과','피부과', '관악구', '봉천동69-12', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GW_5', '아이랑안과','안과', '관악구', '신림동654-12', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

--광진구--
INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GG_5', '눈애안과','안과', '광진구', '화양동6-2', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GG_1', 's리더치과','치과', '광진구', '화양동6-2', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GG_2', '열린피부과','피부과', '광진구', '자양동343-2', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GG_3', '프라임정형외과','정형외과', '광진구', '자양동24-9', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GG_4', '샤인소아과','소아과', '광진구', '중곡동124-9', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

--구로구--
INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GR_1', '연세안과','안과', '구로구', '구로동1124-72', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GR_2', '이디치과','치과', '구로구', '구로동188-72', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GR_3', '닥터스피부과','피부과', '구로구', '구로동35-1', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GR_4', '참튼튼정형외과','정형외과', '구로구', '구로동1126-34', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GR_5', '우리아이들소아과','소아과', '구로구', '구로동584-5', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

--금천구--
INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GH_1', '가산안과','안과', '금천구', '가산동371-28', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GH_2', '더바름치과','치과', '금천구', '시흥동371-28', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');


INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GH_3', '홀인원피부과','피부과', '금천구', '가산동50-28', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GH_4', '가산연세정형외과','정형외과 ', '금천구', '가산동459-11', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

INSERT INTO HPINFO(HNUM,HP_CODE,HP_NAME,HP_INDEX,HP_AREA,HP_ADDRESS,HP_OPEN,HP_CLOSE,HP_LUNCHST,HP_LUNCHFI,HP_PHONE,HP_EMAIL,HP_AVGPOINT,HP_DOCTOR1,HP_DOCTOR2,HP_DOCTOR3)
VALUES(SEQ_HNUM.nextval,'GH_5', '시흥우리들소아과','소아과', '금천구', '시흥동889-8', 9, 17, 13, 14, '010-4123-4444', 'YC@naver.com', 0, ' 정나라 ', '송종기', '운종신');

-- 예약데이터 추가
INSERT INTO RESERVATION VALUES(SEQ_RES_NUM.nextval,'GN_1', '강남내과','내과', '강남구', '역삼동545-1','010-4444-4444','admin123','사용자',12,00,'19/09/1','은팔이','증상불명');
INSERT INTO RESERVATION VALUES(SEQ_RES_NUM.nextval,'GS_2', '강서치과','치과', '강서구', '화곡동125-1','010-4444-4444','admin123','사용자',12,00,'19/09/2','은팔이','증상불명');
INSERT INTO RESERVATION VALUES(SEQ_RES_NUM.nextval,'GB_1', '강북내과','내과', '강북구', '미아동 410-106','010-4444-4444','admin123','사용자',12,00,'19/09/11','은팔이','증상불명');
INSERT INTO RESERVATION VALUES(SEQ_RES_NUM.nextval,'GD_1', '강동내과','내과', '강동구', '천호동 410-106','010-4444-4444','admin123','사용자',12,00,'19/09/11','은팔이','증상불명');
INSERT INTO RESERVATION VALUES(SEQ_RES_NUM.nextval,'YS_5', '기대찬정형외과','정형외과','용산구','신계동52-1','010-4123-4444','admin123','사용자',12,00,'19/02/01','송종기','증상불명');
INSERT INTO RESERVATION VALUES(SEQ_RES_NUM.nextval,'YS_4', '아이꿈','소아청소년과', '용산구', '신창동54-9','010-4123-4444','admin123','사용자',12,00,'19/04/02','송종기','증상불명');
INSERT INTO RESERVATION VALUES(SEQ_RES_NUM.nextval,'YS_3', '더페이스','피부과', '용산구', '도원동35-1','010-4123-4444','admin123','사용자',10,00,'19/05/20','정나라','증상불명');
INSERT INTO RESERVATION VALUES(SEQ_RES_NUM.nextval,'YS_2', '코앤코','이비인후과', '용산구', '이촌동435','010-4123-4444','admin123','사용자',14,00,'18/12/20','정나라','증상불명');
INSERT INTO RESERVATION VALUES(SEQ_RES_NUM.nextval,'YS_1', '바른이치과','치과', '용산구', '갈월동535-1','010-4123-4444','admin123','사용자',15,00,'19/07/30','운종신','증상불명');
INSERT INTO RESERVATION VALUES(SEQ_RES_NUM.nextval,'MP_1', '연세MY바른이치과의원','치과','마포구','동교동 166-13 삼양세븐스프링스','02-337-2282','admin123','사용자',16,00,'19/06/22','김민정','증상불명');
INSERT INTO RESERVATION VALUES(SEQ_RES_NUM.nextval,'YS_5', '기대찬정형외과','정형외과','용산구','신계동52-1','010-4123-4444','admin123','사용자',12,00,'19/09/09','정나라','증상불명');
INSERT INTO RESERVATION VALUES(SEQ_RES_NUM.nextval,'YS_4', '아이꿈','소아청소년과', '용산구', '신창동45-9','010-4123-4444','admin123','사용자',13,00,'19/09/09','송종기','증상불명');
INSERT INTO RESERVATION VALUES(SEQ_RES_NUM.nextval,'YS_4', '아이꿈','소아청소년과', '용산구', '신창동45-9','010-4123-4444','admin123','사용자',14,00,'19/09/09','송종기','증상불명');
INSERT INTO RESERVATION VALUES(SEQ_RES_NUM.nextval,'YS_4', '아이꿈','소아청소년과', '용산구', '신창동45-9','010-4123-4444','admin123','사용자',15,00,'19/09/09','송종기','증상불명');
 INSERT INTO RESERVATION VALUES(SEQ_RES_NUM.nextval,'YS_4', '아이꿈','소아청소년과', '용산구', '신창동45-9','010-4123-4444','admin123','사용자',16,00,'19/09/30','송종기','증상불명');

--리뷰데이터 추가
INSERT INTO REVIEW VALUES(1,SEQ_RE_NUM.nextval,'admin123','장염이 나았어요','19/09/01','GN_1','강남내과',5,5,5,5,5,5,'의사선생님이 너무 친절하게 잘 해주셨어요. 배가 아파서 며칠동안 아무것도 못먹었는데 약 먹고 금방 나았어요!',15,1);
INSERT INTO REVIEW VALUES(2,SEQ_RE_NUM.nextval,'admin123','만족합니다~','19/09/02','GS_2', '강서치과',4.8,5,4,5,5,5,'사랑니가 신경이랑 엄청 가까웠는데도 잘 뽑아주셨어요. 역시 사랑니 전문병원 찾아가길 잘했네요(짝짝)',120,3);
INSERT INTO REVIEW VALUES(3,SEQ_RE_NUM.nextval,'admin123','이상해요','19/09/11','GB_1','강북내과',1.6,1,1,2,2,2,'의사가 돌팔이같아요. 진찰도 대충하고 약을 먹어도 차도가 없어요.',2,10);
INSERT INTO REVIEW VALUES(4,SEQ_RE_NUM.nextval,'admin123','너무 좋아요','19/09/11','GD_1','강동내과',4.2,4,4,4,5,4,'감기가 너무 심했는데 주사맞고 바로 나았어요. 병원도 정말 깨끗해요.',7,0);
INSERT INTO REVIEW VALUES(5,SEQ_RE_NUM.nextval,'admin123','손목이 안나아요','19/02/01','YS_5','기대찬정형외과',3,3,3,3,3,3,'손목이 계속 아파서 갔는데 한달동안 물리치료를 받았는데도 낫지를 않아요ㅠㅠ',1,0);
INSERT INTO REVIEW VALUES(6,SEQ_RE_NUM.nextval,'admin123','원장님 좋아요','19/04/02','YS_4','아이꿈',4.4,5,4,4,5,4,'어른인데도 진료 잘 해주셨어요.',2,0);
INSERT INTO REVIEW VALUES(7,SEQ_RE_NUM.nextval,'admin123','괜찮았어요','19/05/20','YS_3','더페이스',4,4,5,3,4,4,'피부염이 너무 심해져서 갔었는데 처방해주신 연고 바르고 일주일만에 나았어요!!',50,3);
INSERT INTO REVIEW VALUES(8,SEQ_RE_NUM.nextval,'admin123','조금 더러워요','18/12/20','YS_2','코앤코',2.2,2,3,2,2,2,'기계가 너무 구식이고 제대로 세척도 안해놔서 치료받는데 좀 불쾌했어요',2,10);
INSERT INTO REVIEW VALUES(9,SEQ_RE_NUM.nextval,'admin123','이상해요','19/07/30','YS_1','바른이치과',2.4,3,3,2,2,2,'이가 썩어서 갔는데 스케일링만 하고 제대로 진료를 안해주셨어요. 다시 가고싶지 않아요',10,1);
INSERT INTO REVIEW VALUES(10,SEQ_RE_NUM.nextval,'admin123','인생치과!','19/06/22','MP_1','연세MY바른이치과의원',5,5,5,5,5,5,'원장님이 너무 친절하고 하나도 안아프게 진료해주셔요. 충치치료 이만큼 안아픈적 처음이네요. 인생치과!!',100,0);
INSERT INTO REVIEW VALUES(11,SEQ_RE_NUM.nextval,'admin123','친절해요.','19/03/01','YS_5','기대찬정형외과',4.2,4,4,4,5,4,'뼈가 부러진줄알았는데 인대가 늘어난거였네요..^^그래도 잘 봐주셔서 감사합니다.',7,0);
INSERT INTO REVIEW VALUES(12,SEQ_RE_NUM.nextval,'admin123','감사합니다.','19/09/11','YS_4','아이꿈',4.6,4,4,5,5,5,'저희집 아이가 유별난편인데 상관없이 진찰해주셨어요.좋아요',7,0);

--좋아요 데이터 추가
INSERT INTO LIKEINFO VALUES ('admin123',1,1,0);
INSERT INTO LIKEINFO VALUES ('admin123',2,0,1);
INSERT INTO LIKEINFO VALUES ('admin123',5,1,0);
INSERT INTO LIKEINFO VALUES ('admin123',10,1,0);
INSERT INTO LIKEINFO VALUES ('admin123',12,1,0);

COMMIT;